"use client";

const DownloadFeedback = ({
  feedback,
  role,
}: {
  feedback: Feedback;
  role: string;
}) => {
  const handleDownload = () => {
    const content = `
═══════════════════════════════════════════════════
  PREPVERSE — INTERVIEW FEEDBACK REPORT
═══════════════════════════════════════════════════

Role: ${role} Interview
Date: ${feedback.createdAt ? new Date(feedback.createdAt).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "N/A"}
Overall Score: ${feedback.totalScore}/100

───────────────────────────────────────────────────
  FINAL ASSESSMENT
───────────────────────────────────────────────────

${feedback.finalAssessment}

───────────────────────────────────────────────────
  CATEGORY SCORES
───────────────────────────────────────────────────

${feedback.categoryScores.map((cat, i) => `${i + 1}. ${cat.name}: ${cat.score}/100\n   ${cat.comment}`).join("\n\n")}

───────────────────────────────────────────────────
  STRENGTHS
───────────────────────────────────────────────────

${feedback.strengths.map((s, i) => `  ${i + 1}. ${s}`).join("\n")}

───────────────────────────────────────────────────
  AREAS FOR IMPROVEMENT
───────────────────────────────────────────────────

${feedback.areasForImprovement.map((a, i) => `  ${i + 1}. ${a}`).join("\n")}

═══════════════════════════════════════════════════
  Generated by PrepVerse AI Mock Interview Platform
═══════════════════════════════════════════════════
`.trim();

    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `PrepVerse_Feedback_${role.replace(/\s+/g, "_")}_${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleDownload}
      className="flex items-center gap-2 text-sm text-primary-200 hover:text-primary-100 transition-colors cursor-pointer px-4 py-2 rounded-full border border-primary-200/20 hover:border-primary-200/40 hover:bg-primary-200/5"
    >
      📥 Download Report
    </button>
  );
};

export default DownloadFeedback;
